### ISSUE TITLE
TB 63 complains: This add-on could not be installed because it appears to be corrupt.

### ISSUE THREAD

**Issue by tsdh** [exteditor/exteditor#12]
I've checked out the current `master` branch (commit `167d8433e700bf3fecea6da3459f3e1c1c9672fe`), ran `make` and as a result got a file `exteditor_v103.xpi` which I tried to install by choosing `Install Add-on From File...` in TB's Add-ons Manager tab (Hamburger-button >  Add-ons > Add-ons).  After selecting the XPI and confirming, TB showed a red pane at the top of the window with the message **This add-on could not be installed because it appears to be corrupt.** and no further details.

I'm using Thunderbird version 63.0b1.

**Comment by snipsnipsnip** [comment]
Thanks for trying out.
That's strange. Even though v1.0.3 doesn't support Thunderbird 63 yet, it should be rejected with reasons like 'incompatible', not 'corrupt.'
I'm building releases with Ubuntu 14. Could you attach built XPI file?

**Comment by snipsnipsnip** [comment]
Nevermind, [my build](https://github.com/exteditor/exteditor/releases/download/v1.0.3/exteditor_v103.xpi) was also rejected with 'corrupt' message. Looks like TB63 changed something around XPI format, not just some API.

**Comment by nivseg2** [comment]
Is there a version that will work with TB 60.2.1? 

Getting the above error with v1.0 as well as current github.

**Comment by snipsnipsnip** [comment]
Hi, sorry for late reply. Recently Thunderbird 68 got out of beta.

The problem was Thunderbird < 63 requires add-ons to include something called [`manifest.json`](https://developer.thunderbird.net/add-ons/updates/overlays). I added the file in the package and looks like it's working now.

Please try [v2.0.0](https://github.com/exteditor/exteditor/releases/tag/v2.0.0).
