### ISSUE TITLE
Cannot find external editor icon in the customization options

### ISSUE THREAD

**Issue by ghost** [exteditor/exteditor#9]
I've looked in the respective customisation icons windows for both (1) the main Thunderbird window, (2) the compose window, and I can't find the relevant icon.

Admittedly I am hampered by [this longstanding Thunderbird silliness](https://bugzilla.mozilla.org/show_bug.cgi?id=1318901) and [this fairly longstanding problem on Linux Mint](https://github.com/linuxmint/mint-y-theme/issues/79) - and the various ancient and acute problems with Thunderbird's own editor are what makes an extension such as yours as necessity.

But I did install the exteditor extension,

**Comment by jdgblogs** [comment]
I'm having the same problem - Thunderbird version 52.6.0 (64 bit) on Mac OS X High Sierra.  As the OP states, I did install the plugin after compiling it, and it shows in my extensions.  Preferences button does nothing.  I also looked in the main View-Toolbars-Customize and Customize in the new message window.  It's not there.  I would love to see this working so I can use vim or gvim instead of Thunderbird's "editor" and select all and cut (for replies), paste into gvim, edit, select all, copy, paste back into Thunderbird....

**Comment by jdgblogs** [comment]
I'm having the same problem - Thunderbird version 52.6.0 (64 bit) on Mac OS X High Sierra.  As the OP states, I did install the plugin after compiling it, and it shows in my extensions.  Preferences button does nothing.  I also looked in the main View-Toolbars-Customize and Customize in the new message window.  It's not there.  I would love to see this working so I can use vim or gvim instead of Thunderbird's "editor" and select all and cut (for replies), paste into gvim, edit, select all, copy, paste back into Thunderbird.... I should also add, I restarted Thunderbird as required before looking for the icon in either customize listing.

**Comment by holocronweaver** [comment]
Same issue, Ubuntu 16.04 w/ Thunderbird 52.8.0 64-bit. Cloned this git repo, ran `make`, installed XPI in thunderbird, verified in extensions list, but no icon in Customize Toolbar. =(

**Comment by JontAlle** [comment]
have you tried withExEditor, addon for Thunderbird:
It works for me, once you have:
1) installed node.js on your machine, and
2) the module downloaded from
https://addons.mozilla.org/en-US/firefox/addon/withexeditor/
and then you need
3) a local-host code  "index.js" you can get from
https://github.com/asamuzaK/withExEditorHost
It does work if you hack your way through these three items.

**Comment by psz2036** [comment]
When you build from source ZIP file, you need to rename the directory:
the source ZIP unpacks to exteditor-master, you need to rename to exteditor,
before you type `make` in there. Then the xpi created will work fine.

**Comment by reagle** [comment]
I don't understand the exteditor suggestion. Isn't that for firefox? I'm hoping TB exteditor is updated for version 60+.

**Comment by psz2036** [comment]
Yes it is for Thunderbird, not Firefox.
I use Thunderbird version 60.0, with exteditor.

The comment was about how to "build" the XPI file from source: because
someone complained they could not, or that it did not work. But you do
not need to build yourself.

Download the XPI file from
https://github.com/exteditor/exteditor/releases/download/v1.0.3/exteditor_v103.xpi
to your computer. When downloading with Firefox, if you just click that
link then Firefox gets "confused" and thinks the XPI file is for it to
install; you need to right-click and choose SaveAs.

Once you have the XPI file on your computer, in Thunderbird you go to
Tools -> AddOns -> Extensions and click the gear icon at the top, and
select InstallAddOnFromFile.

Cheers, Paul
-- 
Paul Szabo   psz@maths.usyd.edu.au   http://www.maths.usyd.edu.au/u/psz/
School of Mathematics and Statistics   University of Sydney    Australia

**Comment by JontAlle** [comment]
The above email from Paul finally resolved my massive confusion. There are two "plugins"
1) withExEditor: this is used for editing browser pages, such as wiki pages
2) exeditor: this is for editing email
The above email from Paul (psz2036) gives the install instructions for exeditor (Email).

**Comment by rross101** [comment]
I have the same issue - nothing appears in the 'Menu-Tools-Add on Preferences'. I've tried with v202 and with v103, which gives an incompatibility error.

**Comment by snipsnipsnip** [comment]
It is a long-running Thunderbird bug on Mac. Pinned #60 as a notice.
